name: Continuous Delivery Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: zipfile-test
          path: |
            **.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: zipfile-test

        - name: Display structure of downloaded files
          run: ls -R