name: Continuous Integration Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  # [push]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

  discord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Discord Webhook
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Build and deploy"
        GITHUB_JOB_STATUS: ${{ job.status }}
